version: '3.6'
services:
  mariadb:
    image: library/mariadb:10-focal
    deploy:
      resources:
        limits:
          memory: 1gb
    networks:
      - stack
    command: --max_allowed_packet=134217728 --transaction-isolation=READ-UNCOMMITTED --innodb-lock-wait-timeout=10
    environment:
      MYSQL_ROOT_PASSWORD: mariadbP@55
      MYSQL_DATABASE: jahia
      MYSQL_USER: jahia
      MYSQL_PASSWORD: jahia
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.14
    environment:
      - discovery.type=single-node
    deploy:
      resources:
        limits:
          memory: 2gb
    ports:
      - 9200:9200
    networks:
      stack:
  jahia:
    image: jahia/jahia-ee:8.1
    networks:
      - stack
    depends_on:
      - mariadb
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 4gb
    environment:
      DBMS_TYPE: mariadb
      DB_HOST: mariadb
      DB_NAME: jahia
      DB_USER: jahia
      DB_PASS: jahia
      OPERATING_MODE: development
      PROCESSING_SERVER: 'true'
      MAX_RAM_PERCENTAGE: 95
      EXECUTE_PROVISIONING_SCRIPT: 'https://raw.githubusercontent.com/cedfou/provisioning-tutorials/main/03-augmented-search/provisioning.yaml'
networks:
  stack:
